spring.application.name=vintageBooks

spring.datasource.url=jdbc:mysql://localhost:3306/book_rental_system
spring.datasource.username=root
spring.datasource.password=Blue@1434

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
